### ISSUE TITLE
loop redirect

### ISSUE THREAD

**Issue by linux2014linux** [EsupPortail/nginx-auth-cas-lua#6]
My server config is:
```
    server {
        listen 80;
        server_name console.cloud.ll.com;
        location /s1 {
            access_by_lua_block { require('cas').forceAuthentication() }
            root /Users/ll/Software/openrestry/nginx/www;
            index index.html;
        }
    }
```
I access http://console.cloud.ll.com/s1, then it always redirect. Should I modify server config.

**Comment by prigaux** [comment]
Loop happens when the session cookie does not work as expected. Can you check why?

**Comment by linux2014linux** [comment]
> Loop happens when the session cookie does not work as expected. Can you check why?

The domain console.cloud.ll.com is configed in my /etc/hosts:
```
# cas test
127.0.0.1 console.cloud.ll.com
```

I found some log in nginx error.log:
```
2021/03/11 16:06:29 [error] 83658#2233887: *12 [lua] cas.lua:110: _validate(): no resolver defined to resolve "cas.ll.com", client: 127.0.0.1, server: console.cloud.ll.com, request: "GET /s1/?ticket=ST-88-i97h2L8HYFD9pF0KXtlAyUQXRxAliulei07 HTTP/1.1", host: "console.cloud.ll.com"
```
I don't understand why cas.lua can not resolver my hosts domain name. I don't use cas, it works!

**Comment by prigaux** [comment]
AFAIK you can't do this: "resty.http" uses [tcpsock:connect](https://github.com/openresty/lua-nginx-module#tcpsockconnect) which relies on `resolver` which uses a DNS server.

**Comment by linux2014linux** [comment]
OK, thanks!
