### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by Did-IUT51** [EsupPortail/nginx-auth-cas-lua#9]
Hello,

The lua-rest-http lib has changed : we need to download a third file to run nginx-auth-cas-lua : 

wget https://raw.githubusercontent.com/ledgetech/lua-resty-http/master/lib/resty/http_connect.lua

regards,

**Comment by prigaux** [comment]
Ref: https://github.com/ledgetech/lua-resty-http/commit/4bf2e9c52ed06fcb2e8c7ae6cfec824b4ce1677a
